echo "GULBUNTU_ROOT is set as" $GULBUNTU_ROOT

INTERMEDIATE_DIR=$GULBUNTU_ROOT/intermediate

$GULBUNTU_ROOT/scripts/pad.sh
cat $INTERMEDIATE_DIR/stage1 $INTERMEDIATE_DIR/stage2 $INTERMEDIATE_DIR/pad $INTERMEDIATE_DIR/kernel.bin $INTERMEDIATE_DIR/pad2 > $GULBUNTU_ROOT/bin/floppy.img